name: umbrella_echonomics
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_modular: ^6.3.3
  result_dart: ^1.1.1
  equatable: ^2.0.5
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  email_validator: ^3.0.0
  envied: ^0.5.4+1
  parse_server_sdk_flutter: ^8.0.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  fl_chart: ^0.69.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1


flutter:


  uses-material-design: true

  assets:
    - assets/icons/categories/
    - assets/icons/payment_methods/
    - assets/animations/
    - assets/images/

