allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

tasks.withType(JavaCompile) {
    options.forkOptions.javaHome = file("C:/Program Files/Eclipse Adoptium/jdk-17.0.12.7-hotspot")
}
